version: '3'

services:

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: ediogama/nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - db

  app:
    build:
      context: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - ./node/node_modules:/usr/src/app/node_modules
    tty: true
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER_ROOT=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge